<?php

namespace App\Filament\Resources\PaySlips\Pages;

use App\Filament\Resources\PaySlips\PaySlipResource;
use Filament\Actions\CreateAction;
use Filament\Resources\Pages\ListRecords;

class ListPaySlips extends ListRecords
{
    protected static string $resource = PaySlipResource::class;

    protected function getHeaderActions(): array
    {
        return [
            // CreateAction::make(), // Not needed as payslips are autogenerated
        ];
    }
}
